### ISSUE TITLE
When animations switch from one to another, it's not smooth

### ISSUE THREAD

**Issue by jessicayzt** [jessicayzt/cpsc311_proj#1]
I got no idea about this one, it's quite noticeable, maybe we'll just change Jack into a ghost so it'll be a feature not a bug.

**Comment by laurarodgers** [comment]
I'm wondering if putting in an input alias and then centrally stepping frame updates (like in Making Pong) might be worth a try? The flickering seems to be a problem with handling keypresses while non-keypress updates are also occurring.

(It'll take interpolating a bit to do it with subscriptions rather than signals, but I'm convinced there is a conceptually similar subscription implementation that could work)

***
Update: tried a version using one consistent avatar image before totally refactoring the animation. No more flicker (unsurprisingly) but, I noticed a different aspect of probably the same bug:

When you press and hold left to walk left for some distance, and then immediately press and hold right, there's a lag period where the character just stops before reversing direction.

I recommend replicating this on an empty platform.

I think this is also an issue with handling keypresses. 

Before I get too deep into the weeds with this one, I should probably ask: Jessica, how do you want keypress handling to work, and can you explain a bit more about the current code? I don't want to accidentally break something I don't understand.

**Comment by jessicayzt** [comment]
As you've already started work on this I've tentatively assigned you to this. The current implementation of keypress handling is just with key up and key down subscriptions. Do you have more specific questions about the code? Don't worry about accidentally breaking anything, feel free to push a branch up.

**Comment by laurarodgers** [comment]
Took another look into it (just using browser dev console, should've started there 😝 ) and seems like keypress handling/framerate control is not the only issue.
The worst of the flickering is coming from delayed loading of avatar images.

If we are going to use images as big as dear Jack we will need to find a way to preload assets and keep them persistently available, because on-demand they aren't loading anywhere near fast enough to render.

As the version that only uses one image (but still updates it on changes in action and direction) has no flickering, it looks like images in persistent use are cached well enough.
I'm looking at a solution using Group in Collage that basically shows/hides layers, will push when I'm done. 

This is a messy mess uggo solution so if anyone has any ideas for more elegant ways to tackle this please let me know. 

(I feel like I'm trying to un-elm elm on my second day working on this. What even.)

I haven't found any existing Elm games using large-ish images for frequent real-time updates, so it looks like we're going blind for this one, unless anyone has found an example in which case pleaaaase post.

😃

**Comment by jessicayzt** [comment]
That makes sense, as the Jack animations are all quite large. As we scale them down anyways, maybe compressing them by reducing some frames/size/colour would help?

As Joey mentioned, a more sophisticated game with issues is better than a simple game with no issues, at least now we have something to complain about Elm ;) (Plus I love dear Jack)

When the proof-of-concept doc is up and running, I'll join in and take some stabs at this as well.

**Comment by jessicayzt** [comment]
Bad news, even after I reduced all the Jack animations to ~50KB each, the flicker is still there. However, it is less frequent. I think the Collage.group solution would work, even if it's messy. We'd definitely have something to write about for the final report ;)

I do have something else I'm going to try, which is loading them all in constants in the View module as Elm is eager. I'll take a stab at this later.

**Comment by jessicayzt** [comment]
The constants idea didn't work, looks like it's going to be Collage.group D:
