### ISSUE TITLE
Effects from units and score should be based on time, not on the number of times the update function is called

### ISSUE THREAD

**Issue by jessicayzt** [jessicayzt/cpsc311_proj#18]
The effects from units and the score are updating more often then they should be because they are a function of the number of times the update function is called and not the time elapsed -Karen

**Comment by vanderkooi** [comment]
@karenhong, score is based on whether the character is side-scrolling or not, so I don't think score should rely on time. Otherwise our character could just stand there and rack up the points.

I took a look at changing this for the invincibility and speed but I'm not fully sure how to integrate the time updates with these time limits. For the demo/poster session, I'm keeping invincibility and speed frame-based; perhaps we can talk more about the implementation on Friday?

**Comment by karenhong** [comment]
@vanderkooi Yes, you're right. The score should rely on the side-scrolling, just the time spent side-scrolling. I just did a terrible job at explaining this the first time around. However, the score is getting updated more often than it should and will vary as the browser's event loop varies. The game loop works like this:

Each time we get a time update, we are given the number of milliseconds since the last render  (usually a value from around 20ms to 50ms or more depending on the browser). Since the time difference between frames is inconsistent, we need extra logic to make our animations smooth. 

To give you an example of how the code works, let's say for example that the elapsed time from Animation.diff is 30ms. The updateMotion function increases the scene by 15ms each time it is run. So, in this case, we run the updateMotion twice before passing the model on to render. Everything looks great because our scene is now exactly 30ms in the future. Now, let's say that the elapsed time is actually 40ms. We run updateMotion  twice and the scene is now 30ms ahead but we now find ourselves in the "middle of a frame" because the real time is 10ms ahead of us. In order to fix this, we run the motionUpdate function one last time, passing in a motionMultiplier. The motionMultiplier is given by dividing the leftover lag (10ms in this example) by the msPerUpdate (15ms). This increases the entire scene by our leftover milliseconds and puts us 40ms ahead, exactly where we want to be. 

To read more about this, the Playing Catch up section of this article explains it really well: http://gameprogrammingpatterns.com/game-loop.html

**Comment by karenhong** [comment]
It's that extra time we run updateMotion that is messing up the health and score updates. If we make them a function of time, it will no longer be inconsistent. For the score, it would mean keeping track of the the time spent scrolling forwards and increasing the score based on a function of that. Similarly with health, it would be decreasing or increasing the health based on the amount of time the avatar is in contact with the object instead of the number of times the update function is run. 

Anyways, we can discuss more on Friday. The inconsistencies aren't very noticeable and nothing to stress about for the presentation.

**Comment by vanderkooi** [comment]
Ah, I see. Thanks for the great explanation and the helpful article!

I've updated my invincibility branch with those changes. I just use the multiplier to multiply the normal decrements in the checkTime methods and changed those methods to Float instead of Int. I wanted to keep Score as an int, so I just multiply the normal score increment and round up to preserve that.
